/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ddc39d",
        "surface-container-high": "#e6e8ea",
        "surface-bright": "#f7f9fb",
        "error-container": "#ffdad6",
        "surface-dim": "#d8dadc",
        "on-secondary-fixed-variant": "#003ea8",
        "inverse-on-surface": "#eff1f3",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fefcff",
        "surface-tint": "#545f73",
        "on-primary-fixed": "#111c2d",
        "tertiary-container": "#35260c",
        "on-secondary-fixed": "#00174b",
        "secondary-fixed-dim": "#b4c5ff",
        "surface-container-low": "#f2f4f6",
        "on-primary-fixed-variant": "#3c475a",
        "outline": "#75777d",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-fixed-variant": "#564427",
        "outline-variant": "#c5c6cd",
        "on-error-container": "#93000a",
        "secondary-container": "#316bf3",
        "surface-container": "#eceef0",
        "on-surface-variant": "#45474c",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#d8e3fb",
        "tertiary-fixed": "#fadfb8",
        "on-error": "#ffffff",
        "primary": "#091426",
        "secondary-fixed": "#dbe1ff",
        "primary-container": "#1e293b",
        "surface": "#f7f9fb",
        "on-surface": "#191c1e",
        "inverse-surface": "#2d3133",
        "secondary": "#0051d5",
        "inverse-primary": "#bcc7de",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed": "#271902",
        "tertiary": "#1e1200",
        "primary-fixed-dim": "#bcc7de",
        "background": "#f7f9fb",
        "on-primary": "#ffffff",
        "on-primary-container": "#8590a6",
        "on-tertiary-container": "#a38c6a",
        "on-background": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a"
      },
      fontFamily: {
        ans: ['Inter', 'sans-serif'],
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
